### ISSUE TITLE
Exception ImageReadException

### ISSUE THREAD

**Issue by jaffarhussain1011** [robertvazan/sourceafis-java#11]
i am using netbeans and buil , run operations are successful but 
I am getting following error while running jar file

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/sanselan/ImageReadException
	at com.machinezoo.sourceafis.FingerprintTemplate.create(FingerprintTemplate.java:96)
	at com.machinezoo.sourceafis.MainClass.main(MainClass.java:47)
Caused by: java.lang.ClassNotFoundException: org.apache.sanselan.ImageReadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

My main class
```java
package com.machinezoo.sourceafis;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class MainClass {

    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ANSI_BLACK = "\u001B[30m";
    public static final String ANSI_RED = "\u001B[31m";
    public static final String ANSI_GREEN = "\u001B[32m";
    public static final String ANSI_YELLOW = "\u001B[33m";
    public static final String ANSI_BLUE = "\u001B[34m";
    public static final String ANSI_PURPLE = "\u001B[35m";
    public static final String ANSI_CYAN = "\u001B[36m";
    public static final String ANSI_WHITE = "\u001B[37m";

    public static void main(String[] args) {
        try {
            String probPath = "/var/www/java/robertvazan-sourceafis-java-6db53f9947c0/resources/prob.tif";
            String candidatePath = "/var/www/java/robertvazan-sourceafis-java-6db53f9947c0/resources/101_7.tif";
            System.out.printf("The culprit: ");
            byte[] probeImage = Files.readAllBytes(Paths.get(probPath));
            byte[] candidateImage = Files.readAllBytes(Paths.get(candidatePath));
            File folder = new File("resources");
            File[] listOfFiles = folder.listFiles();

            for (int i = 0; i < listOfFiles.length; i++) {
              if (listOfFiles[i].isFile()) {
                System.out.println("File " + listOfFiles[i].getName());
              } else if (listOfFiles[i].isDirectory()) {
                System.out.println("Directory " + listOfFiles[i].getName());
              }
            }
            FingerprintTemplate probe = new FingerprintTemplate().dpi(500).create(probeImage);
            List<UserDetails> candidates = new ArrayList<>();
            UserDetails candidate = new UserDetails();
            candidate.id = 1;
            candidate.name = "XYZ";
            candidate.template = new FingerprintTemplate().dpi(500).create(candidateImage);
            candidates.add(candidate);
            UserDetails culprit = candidate.find(probe, candidates);
            if (culprit == null) {
                System.out.printf("unable to find match");
            } else {
                System.out.printf("The culprit: " + ANSI_RED + "%s", culprit.name);
            }
        

        } catch (IOException e) {
//            e.printStackTrace();
            System.out.printf("Exception occurred");
        }
    }
}

class UserDetails {

    int id;
    String name;
    FingerprintTemplate template;

    UserDetails find(FingerprintTemplate probe, Iterable<UserDetails> candidates) {
        FingerprintMatcher matcher = new FingerprintMatcher()
                .index(probe);
        UserDetails match = null;
        double high = 0;
        for (UserDetails candidate : candidates) {
            double score = matcher.match(candidate.template);
            if (score > high) {
                high = score;
                match = candidate;
            }
        }
        double threshold = 40;
        return high >= threshold ? match : null;
    }
}
```

**Comment by robertvazan** [comment]
Are you using Maven to pull in all the dependencies?

**Comment by jaffarhussain1011** [comment]
Yes  I am using maven to pull dependencies

**Comment by jaffarhussain1011** [comment]
From POM file
<version>3.4.1</version>

**Comment by jaffarhussain1011** [comment]
I have downloaded from https://bitbucket.org/robertvazan/sourceafis-java/src default branch

**Comment by robertvazan** [comment]
Are you rebuilding from SourceAFIS sources, just with this MainClass added?

**Comment by robertvazan** [comment]
IMO, something is wrong with your Maven setup. Are you sure dependencies are being pulled in? It looks like you opened the project in NetBeans as NetBeans project, not Maven project, and Maven dependencies are not being resolved.

**Comment by robertvazan** [comment]
Look here:

https://platform.netbeans.org/tutorials/nbm-maven-quickstart.html

Did you pick "Project with Existing POM" on the right?

**Comment by robertvazan** [comment]
BTW, I don't see any reason for using SourceAFIS sources directly. You should just reference SourceAFIS as a Maven dependency. That would make definitely sure that dependencies of SourceAFIS are pulled in as well.

**Comment by jaffarhussain1011** [comment]
> Look here:
> 
> https://platform.netbeans.org/tutorials/nbm-maven-quickstart.html
> 
> Did you pick "Project with Existing POM" on the right?

Yes I did this. When i do build and run from netbeans this code works flawlessly.

**Comment by jaffarhussain1011** [comment]
> BTW, I don't see any reason for using SourceAFIS sources directly. You should just reference SourceAFIS as a Maven dependency. That would make definitely sure that dependencies of SourceAFIS are pulled in as well.

I will try this too.

**Comment by robertvazan** [comment]
Aha. I missed the part about JAR. I thought you get this exception when running the code in NetBeans. That means incorrect JAR packaging. Dependencies are not included in JAR. This is not a SourceAFIS issue then. You need to figure out how to include Maven dependencies in the JAR file when building in NetBeans. That's NetBeans question.

**Comment by digital-frog** [comment]
Could you share the solution to your problem?
I'm having the same error message.
