### ISSUE TITLE
Unsupported image format

### ISSUE THREAD

**Issue by sergioluc** [robertvazan/sourceafis-java#21]
Hi !!! I'm working about fingerprint verificaition now, and I have a problem about the image format. 

I have Intellij as IDE, and using sourceafis-3.8.1.jar.
Below my sample code:

 try {
            FingerprintTemplate probe = new FingerprintTemplate (
                    new FingerprintImage ()
                            .dpi ( 500 )
                            .decode (Files.readAllBytes (Paths.get ( "src/image1.jpg" ))));
            FingerprintTemplate candidate = new FingerprintTemplate (
                    new FingerprintImage ()
                            .dpi ( 500 )
                            .decode (Files.readAllBytes (Paths.get ( "src/image2.jpg" ))));
}
And the error is like this:
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported image format [ImageIO = 'java.lang.NoClassDefFoundError: com/machinezoo/noexception/Exceptions -> java.lang.ClassNotFoundException: com.machinezoo.noexception.Exceptions', Sanselan = 'java.lang.NoClassDefFoundError: com/machinezoo/noexception/Exceptions -> java.lang.ClassNotFoundException: com.machinezoo.noexception.Exceptions', WSQ = 'java.lang.IllegalArgumentException: This is not a WSQ image.', Android = 'java.lang.UnsupportedOperationException: Image decoder is not available.'].
	at com.machinezoo.sourceafis.ImageDecoder.decodeAny(ImageDecoder.java:79)
	at com.machinezoo.sourceafis.FingerprintImage.decode(FingerprintImage.java:84)
	at MaintTest.main(MaintTest.java:17)

**Comment by robertvazan** [comment]
This is your problem:

    java.lang.NoClassDefFoundError: com/machinezoo/noexception/Exceptions

One of the dependency libraries is missing. Use maven or other dependency management tool to pull in all the dependencies.
