### ISSUE TITLE
error when running this code

### ISSUE THREAD

**Issue by rizadp51** [robertvazan/sourceafis-java#9]
File sdCard = Environment.getExternalStorageDirectory();
                File dir = new File(sdCard.getAbsolutePath() + "/rio/1541183782271.jpg");

                Bitmap probe = BitmapFactory.decodeFile(dir.getAbsolutePath());

                ByteArrayOutputStream stream = new ByteArrayOutputStream();

                probe.compress(Bitmap.CompressFormat.PNG, 100, stream);

                probeImage = stream.toByteArray();
                stream.reset();

                probeTemplate = new FingerprintTemplate()
                        .dpi(500).create(probeImage);

                sdCard = Environment.getExternalStorageDirectory();
                dir = new File(sdCard.getAbsolutePath() + "/rio/1541183782271.jpg");

                Bitmap candidate = BitmapFactory.decodeFile(dir.getAbsolutePath());

                stream = new ByteArrayOutputStream();

                candidate.compress(Bitmap.CompressFormat.PNG, 100, stream);

                candidateImage = stream.toByteArray();
                stream.reset();

                candidateTemplate = new FingerprintTemplate()
                        .dpi(500).create(candidateImage);

                double score = fm.index(candidateTemplate).match(candidateTemplate);

the error is:

11-10 23:28:00.681 7602-7602/com.belleindonesia.fingerprint2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.belleindonesia.fingerprint2, PID: 7602
    java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/util/function/Function;
        at com.machinezoo.sourceafis.TemplateBuilder.decodeImage(TemplateBuilder.java:151)
        at com.machinezoo.sourceafis.TemplateBuilder.extract(TemplateBuilder.java:25)
        at com.machinezoo.sourceafis.FingerprintTemplate.create(FingerprintTemplate.java:97)
        at com.belleindonesia.fingerprint2.MainActivity$5.onClick(MainActivity.java:248)
        at android.view.View.performClick(View.java:4781)
        at android.view.View$PerformClick.run(View.java:19874)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.function.Function" on path: DexPathList[[zip file "/data/app/com.belleindonesia.fingerprint2-1/base.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.belleindonesia.fingerprint2-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.belleindonesia.fingerprint2-1/lib/arm, /vendor/lib, /system/lib, /data/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.machinezoo.sourceafis.TemplateBuilder.decodeImage(TemplateBuilder.java:151) 
        at com.machinezoo.sourceafis.TemplateBuilder.extract(TemplateBuilder.java:25) 
        at com.machinezoo.sourceafis.FingerprintTemplate.create(FingerprintTemplate.java:97) 
        at com.belleindonesia.fingerprint2.MainActivity$5.onClick(MainActivity.java:248) 
        at android.view.View.performClick(View.java:4781) 
        at android.view.View$PerformClick.run(View.java:19874) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) 
    	Suppressed: java.lang.ClassNotFoundException: java.util.function.Function
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 15 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

.....

please help me, im new developer

**Comment by robertvazan** [comment]
SourceAFIS doesn't support Android yet. It uses ImageIO API, which is not implemented in Android JVM. Some people managed to make it work by modifying the source code:

https://sourceforge.net/p/sourceafis/discussion/1051112/thread/ad581827/
